/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardDirectAdminRouteRouteImport } from './routes/dashboard/direct-admin/route'
import { Route as DashboardNutritionistRouteRouteImport } from './routes/dashboard/nutritionist/route'
import { Route as DashboardAdminFoodItemsIndexRouteImport } from './routes/dashboard/admin/food-items/index'
import { Route as DashboardAdminFoodItemsFoodItemIdRouteImport } from './routes/dashboard/admin/food-items/$foodItemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDirectAdminRouteRoute =
  DashboardDirectAdminRouteRouteImport.update({
    id: '/direct-admin',
    path: '/direct-admin',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardNutritionistRouteRoute =
  DashboardNutritionistRouteRouteImport.update({
    id: '/nutritionist',
    path: '/nutritionist',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdminFoodItemsIndexRoute =
  DashboardAdminFoodItemsIndexRouteImport.update({
    id: '/food-items/',
    path: '/food-items/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminFoodItemsFoodItemIdRoute =
  DashboardAdminFoodItemsFoodItemIdRouteImport.update({
    id: '/food-items/$foodItemId',
    path: '/food-items/$foodItemId',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/direct-admin': typeof DashboardDirectAdminRouteRoute
  '/dashboard/nutritionist': typeof DashboardNutritionistRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/food-items/$foodItemId': typeof DashboardAdminFoodItemsFoodItemIdRoute
  '/dashboard/admin/food-items/': typeof DashboardAdminFoodItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/direct-admin': typeof DashboardDirectAdminRouteRoute
  '/dashboard/nutritionist': typeof DashboardNutritionistRouteRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/food-items/$foodItemId': typeof DashboardAdminFoodItemsFoodItemIdRoute
  '/dashboard/admin/food-items': typeof DashboardAdminFoodItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/direct-admin': typeof DashboardDirectAdminRouteRoute
  '/dashboard/nutritionist': typeof DashboardNutritionistRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/food-items/$foodItemId': typeof DashboardAdminFoodItemsFoodItemIdRoute
  '/dashboard/admin/food-items/': typeof DashboardAdminFoodItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/direct-admin'
    | '/dashboard/nutritionist'
    | '/dashboard/'
    | '/dashboard/admin/food-items/$foodItemId'
    | '/dashboard/admin/food-items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/direct-admin'
    | '/dashboard/nutritionist'
    | '/dashboard'
    | '/dashboard/admin/food-items/$foodItemId'
    | '/dashboard/admin/food-items'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/complete-profile'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/direct-admin'
    | '/dashboard/nutritionist'
    | '/dashboard/'
    | '/dashboard/admin/food-items/$foodItemId'
    | '/dashboard/admin/food-items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/direct-admin': {
      id: '/dashboard/direct-admin'
      path: '/direct-admin'
      fullPath: '/dashboard/direct-admin'
      preLoaderRoute: typeof DashboardDirectAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nutritionist': {
      id: '/dashboard/nutritionist'
      path: '/nutritionist'
      fullPath: '/dashboard/nutritionist'
      preLoaderRoute: typeof DashboardNutritionistRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/food-items/': {
      id: '/dashboard/admin/food-items/'
      path: '/food-items'
      fullPath: '/dashboard/admin/food-items/'
      preLoaderRoute: typeof DashboardAdminFoodItemsIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/food-items/$foodItemId': {
      id: '/dashboard/admin/food-items/$foodItemId'
      path: '/food-items/$foodItemId'
      fullPath: '/dashboard/admin/food-items/$foodItemId'
      preLoaderRoute: typeof DashboardAdminFoodItemsFoodItemIdRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
  }
}

interface DashboardAdminRouteRouteChildren {
  DashboardAdminFoodItemsFoodItemIdRoute: typeof DashboardAdminFoodItemsFoodItemIdRoute
  DashboardAdminFoodItemsIndexRoute: typeof DashboardAdminFoodItemsIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminFoodItemsFoodItemIdRoute:
    DashboardAdminFoodItemsFoodItemIdRoute,
  DashboardAdminFoodItemsIndexRoute: DashboardAdminFoodItemsIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardDirectAdminRouteRoute: typeof DashboardDirectAdminRouteRoute
  DashboardNutritionistRouteRoute: typeof DashboardNutritionistRouteRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardDirectAdminRouteRoute: DashboardDirectAdminRouteRoute,
  DashboardNutritionistRouteRoute: DashboardNutritionistRouteRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
